ALTER TABLE urunler ADD COLUMN IF NOT EXISTS sescim_fiyat DECIMAL(10,2);
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS sescim_indirimli_fiyat DECIMAL(10,2);
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
